---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: debian-test-sa
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: debian-test
  namespace: default
spec:
  serviceAccountName: debian-test-sa
  containers:
  - name: sleep
    image: europe-west9-docker.pkg.dev/sandbox-mgoulin/kube-docker-dockerio-repo-proxy/library/debian
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - "sleep"
      - "100000000"
  restartPolicy: Never
